name: CI

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['18', '20']

    name: Node ${{ matrix.node }} build

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies
        with:
          node-version: ${{ matrix.node }}

      - name: Build, test and lint all projects (except website)
        run: yarn nx run-many -t build lint test --exclude=rxjs.dev

      - name: rxjs lint
        run: yarn workspace rxjs lint
      - name: rxjs build
        run: yarn workspace rxjs build
      - name: rxjs test
        run: yarn workspace rxjs test
      - name: rxjs dtslint
        run: yarn workspace rxjs dtslint
      - name: rxjs test:import
        run: yarn workspace rxjs test:import
      - name: rxjs test:esm
        run: yarn workspace rxjs test:esm
      - name: rxjs.dev build
        run: yarn workspace rxjs.dev build --prod
      - name: rxjs.dev test
        run: yarn workspace rxjs.dev test --watch=false --browsers=ChromeHeadless
